$ErrorActionPreference='Stop'
$enc=[Text.Encoding]::GetEncoding(28591)
function R1([string]$p,[string]$o,[string]$n){
  $t=$enc.GetString([IO.File]::ReadAllBytes($p)); $nl=if($t.Contains("`r`n")){"`r`n"}else{"`n"}
  $o=$o.Replace("`n",$nl); $n=$n.Replace("`n",$nl)
  $c=([regex]::Matches($t,[regex]::Escape($o))).Count; if($c-ne 1){throw "$p expected 1 match, found $c"}
  [IO.File]::WriteAllBytes($p,$enc.GetBytes($t.Replace($o,$n)))
}
$h='ExtremeCopy/Core/XCAsyncFileDataTransFilter.h'; $a='ExtremeCopy/Core/XCAsyncFileDataTransFilter.cpp'; $d='ExtremeCopy/Core/XCDestinationFilter.cpp'; $cfg='ExtremeCopy/App/XCConfiguration.cpp'
R1 $h '#include <set>' "#include <set>`n#include <atomic>"
R1 $h "`tbool`t`t`t`t`t`t`tm_bWriteThreadEnd;" "`tstd::atomic<bool>`t`t`t`t`tm_bWriteThreadEnd;"
R1 $a 'm_bWriteThreadEnd = true;' 'm_bWriteThreadEnd.store(true,std::memory_order_release) ;'
R1 $a "`tm_bWriteThreadEnd = true;" "`tm_bWriteThreadEnd.store(true,std::memory_order_release) ;"
R1 $a "`tif(m_hWriteDataReadyEvent==NULL)`n`t{`n`t`tm_hWriteDataReadyEvent = ::CreateEvent(NULL,FALSE,FALSE,NULL) ;`n`t}`n`n`tif(m_hThread==NULL)`n`t{`n`t`tm_bWriteThreadEnd = false;`n`t`tm_hThread = (HANDLE)::_beginthreadex(NULL,0,ThreadFunc,this,0,NULL) ;`n`t}`n`n`treturn CXCFileDataCacheTransFilter::OnInitialize() ;" "`tif(m_hWriteDataReadyEvent==NULL)`n`t{`n`t`tm_hWriteDataReadyEvent = ::CreateEvent(NULL,FALSE,FALSE,NULL) ;`n`t`tif(m_hWriteDataReadyEvent==NULL) return false ;`n`t}`n`n`tif(m_hThread==NULL)`n`t{`n`t`tm_bWriteThreadEnd.store(false,std::memory_order_release) ;`n`t`tm_hThread = (HANDLE)::_beginthreadex(NULL,0,ThreadFunc,this,0,NULL) ;`n`t`tif(m_hThread==NULL)`n`t`t{`n`t`t`tm_bWriteThreadEnd.store(true,std::memory_order_release) ;`n`t`t`t::CloseHandle(m_hWriteDataReadyEvent) ; m_hWriteDataReadyEvent=NULL ;`n`t`t`treturn false ;`n`t`t}`n`t}`n`n`tif(!CXCFileDataCacheTransFilter::OnInitialize())`n`t{`n`t`tm_bWriteThreadEnd.store(true,std::memory_order_release) ;`n`t`t::SetEvent(m_hWriteDataReadyEvent) ;`n`t`t::WaitForSingleObject(m_hThread,INFINITE) ;`n`t`t::CloseHandle(m_hThread) ; m_hThread=NULL ;`n`t`t::CloseHandle(m_hWriteDataReadyEvent) ; m_hWriteDataReadyEvent=NULL ;`n`t`treturn false ;`n`t}`n`treturn true ;"
$t=$enc.GetString([IO.File]::ReadAllBytes($a)); $t=$t.Replace('PT_BREAK_IF(m_bWriteThreadEnd);','PT_BREAK_IF(m_bWriteThreadEnd.load(std::memory_order_acquire));').Replace('PT_BREAK_IF(m_bWriteThreadEnd ||','PT_BREAK_IF(m_bWriteThreadEnd.load(std::memory_order_acquire) ||').Replace('while(!m_bWriteThreadEnd ||','while(!m_bWriteThreadEnd.load(std::memory_order_acquire) ||'); [IO.File]::WriteAllBytes($a,$enc.GetBytes($t))
R1 $cfg "`tconfig.uLastCheckUpdateTime = (time_t)::GetPrivateProfileInt(pSectionName,_T(\"LastCheckTime\"),0,szIniFile) ;" "`tTCHAR szLastCheckTime[64] = {0} ;`n`t::GetPrivateProfileString(pSectionName,_T(\"LastCheckTime\"),_T(\"0\"),szLastCheckTime,sizeof(szLastCheckTime)/sizeof(TCHAR),szIniFile) ;`n`tTCHAR* pLastCheckEnd = NULL ;`n`t__int64 nLastCheckTime = ::_tcstoi64(szLastCheckTime,&pLastCheckEnd,10) ;`n`tconfig.uLastCheckUpdateTime = (pLastCheckEnd!=szLastCheckTime && *pLastCheckEnd==0 && nLastCheckTime>=0) ? (time_t)nLastCheckTime : (time_t)0 ;"
R1 $d "`t`t`t`tunsigned __int64 dwLow = dfi.bNoBuf ? ALIGN_SIZE_UP(dfi.uRemainSize,m_StorageInfo.nSectorSize) : dfi.uRemainSize ;`n`t`t`t`tDWORD dwHi = (DWORD)(dwLow>>32) ;`n`nEXCEPTION_RETRY_ALLOCATEFILESIZE://" "`t`t`t`tLARGE_INTEGER liAllocateSize ;`n`t`t`t`tliAllocateSize.QuadPart = (LONGLONG)(dfi.bNoBuf ? ALIGN_SIZE_UP(dfi.uRemainSize,m_StorageInfo.nSectorSize) : dfi.uRemainSize) ;`n`nEXCEPTION_RETRY_ALLOCATEFILESIZE://"
R1 $d "`t`t`t`tif(::SetFilePointer(dfi.hFile, (DWORD)dwLow, (PLONG)&dwHi, FILE_BEGIN)!=INVALID_SET_FILE_POINTER`n`t`t`t`t`t&& ::SetEndOfFile(dfi.hFile))`n`t`t`t`t{`n`t`t`t`t`t::SetFilePointer(dfi.hFile, 0, NULL, FILE_BEGIN);`n`t`t`t`t}" "`t`t`t`tLARGE_INTEGER liZero ; liZero.QuadPart = 0 ;`n`t`t`t`tif(::SetFilePointerEx(dfi.hFile,liAllocateSize,NULL,FILE_BEGIN) && ::SetEndOfFile(dfi.hFile)`n`t`t`t`t`t&& ::SetFilePointerEx(dfi.hFile,liZero,NULL,FILE_BEGIN))`n`t`t`t`t{`n`t`t`t`t}"
R1 $d "`t`t`tif((*it).uRemainSize==0 && (*it).bNoBuf )`n`t`t`t{`n`t`t`t`t_ASSERT(!bOverCurIt) ;`n`t`t`t`tLARGE_INTEGER liFileSize ;`n`t`t`t`tliFileSize.QuadPart = (LONGLONG)(*it).pSfi->nFileSize ;`n`t`t`t`tif(::SetFilePointerEx((*it).hFile,liFileSize,NULL,FILE_BEGIN) && ::SetEndOfFile((*it).hFile))`n`t`t`t`t{`n`t`t`t`t`tbDelete = false ;`n`t`t`t`t}//" "`t`t`tif((*it).uRemainSize==0 && (*it).bNoBuf )`n`t`t`t{`n`t`t`t`t_ASSERT(!bOverCurIt) ;`n`t`t`t`tif(((*it).pSfi->nFileSize % m_StorageInfo.nSectorSize)==0)`n`t`t`t`t{`n`t`t`t`t`tbDelete = false ;`n`t`t`t`t}`n`t`t`t`telse`n`t`t`t`t{`n`t`t`t`t`t::CloseHandle((*it).hFile) ; (*it).hFile=INVALID_HANDLE_VALUE ;`n`t`t`t`t`tHANDLE hTrim = ::CreateFile((*it).strFileName.c_str(),GENERIC_WRITE,FILE_SHARE_READ,NULL,OPEN_EXISTING,FILE_FLAG_SEQUENTIAL_SCAN,NULL) ;`n`t`t`t`t`tif(hTrim!=INVALID_HANDLE_VALUE)`n`t`t`t`t`t{`n`t`t`t`t`t`tLARGE_INTEGER liFileSize ; liFileSize.QuadPart=(LONGLONG)(*it).pSfi->nFileSize ;`n`t`t`t`t`t`tif(::SetFilePointerEx(hTrim,liFileSize,NULL,FILE_BEGIN) && ::SetEndOfFile(hTrim)) bDelete=false ;`n`t`t`t`t`t`t::CloseHandle(hTrim) ;`n`t`t`t`t`t}`n`t`t`t`t}`n`t`t`t`t}//"
git diff --check
$changed=@(git diff --name-only); $expected=@($h,$a,$d,$cfg); if($changed.Count-ne 4 -or ($changed|?{$_ -notin $expected})){throw "unexpected changed files: $changed"}
